apiVersion: apps/v1

kind: Deployment

metadata:
  name: backend
  namespace: mlops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

      - name: backend

        image: backend-local:latest

        imagePullPolicy: Never

        ports:
        - containerPort: 5000

        env:

        - name: MYSQL_HOST
          value: mysql

        - name: MYSQL_PORT
          value: "3306"

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD

        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE