services:

  frontend:

    image: 920687103858.dkr.ecr.us-east-1.amazonaws.com/frontend-heartdisease-and-diabetes-prediction:latest

    container_name: frontend_container

    restart: always



  backend:

    image: 920687103858.dkr.ecr.us-east-1.amazonaws.com/backend-heartdisease-and-diabetes-prediction:latest

    container_name: backend_container

    restart: always

    env_file:
      - ./backend/.env

    depends_on:
      - mysql

    volumes:
      - model_data:/app/models

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3



  mysql:

    image: mysql:8

    container_name: mysql_container

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: healthdb

    volumes:
      - mysql_data:/var/lib/mysql



  nginx:

    image: 920687103858.dkr.ecr.us-east-1.amazonaws.com/nginx-heartdisease-and-diabetes-prediction:latest

    container_name: nginx_container

    restart: always

    ports:
      - "80:80"

    depends_on:
      - frontend
      - backend

    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3



  prometheus:

    image: prom/prometheus

    container_name: prometheus_container

    restart: always

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - backend



  grafana:

    image: grafana/grafana

    container_name: grafana_container

    restart: always

    ports:
      - "3000:3000"

    depends_on:
      - prometheus



  node_exporter:

    image: prom/node-exporter

    container_name: node_exporter_container

    restart: always

    ports:
      - "9100:9100"



  cadvisor:

    image: gcr.io/cadvisor/cadvisor:latest

    container_name: cadvisor_container

    restart: always

    ports:
      - "8080:8080"

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

    privileged: true



  loki:

    image: grafana/loki:latest

    container_name: loki_container

    restart: always

    ports:
      - "3100:3100"

    command: -config.file=/etc/loki/local-config.yaml

    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml



  promtail:

    image: grafana/promtail:latest

    container_name: promtail_container

    restart: always

    volumes:
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock

    command: -config.file=/etc/promtail/config.yml

    depends_on:
      - loki



volumes:
  mysql_data:
  model_data: