apiVersion: v1

kind: Secret

metadata:
  name: mysql-secret
  namespace: mlops

type: Opaque

stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: healthdb
  MYSQL_USER: root
  MYSQL_PASSWORD: password