apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}

spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}

    spec:
      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: {{ .Values.frontend.name }}

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.frontend.containerPort }}

          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu }}
              memory: {{ .Values.frontend.resources.requests.memory }}

            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu }}
              memory: {{ .Values.frontend.resources.limits.memory }}