namespace: mlops

backend:
  name: backend

  image:
    repository: 920687103858.dkr.ecr.us-east-1.amazonaws.com/backend-heartdisease-and-diabetes-prediction
    tag: initial

  replicas: 1
  containerPort: 5000

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"

    limits:
      cpu: "500m"
      memory: "1Gi"

frontend:
  name: frontend

  image:
    repository: 920687103858.dkr.ecr.us-east-1.amazonaws.com/frontend-heartdisease-and-diabetes-prediction
    tag: initial

  replicas: 1
  containerPort: 80

  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"

    limits:
      cpu: "100m"
      memory: "128Mi"

mysql:
  name: mysql
  image: mysql:8
  replicas: 1
  containerPort: 3306
  storage: 1Gi

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"

    limits:
      cpu: "500m"
      memory: "1Gi"

secret:
  mysqlRootPassword: password
  mysqlUser: root
  mysqlPassword: password
  mysqlDatabase: healthdb

ingress:
  host: ""

hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 50