name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  docker-build-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-heartdisease-and-diabetes-prediction:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-heartdisease-and-diabetes-prediction:latest

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-heartdisease-and-diabetes-prediction:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-heartdisease-and-diabetes-prediction:latest

      - name: Build and Push Nginx Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-heartdisease-and-diabetes-prediction:latest ./nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-heartdisease-and-diabetes-prediction:latest